import type { NextPage } from "next";
import Head from "next/head";
import { CeList } from "../components/CeList";
import styles from "../styles/Home.module.css";
import { CraftEssence, SortOption } from "../types";
import fsPromises from "fs/promises";
import path from "path";
import { CSSProperties, useState } from "react";

type Props = {
  craftEssences: CraftEssence[];
};

export async function getStaticProps() {
  const filePath = path.join(process.cwd(), "public/results.json");
  const jsonData = await fsPromises.readFile(filePath);
  const craftEssences = JSON.parse(jsonData as unknown as string);

  return {
    props: {
      craftEssences,
    },
  };
}

const Home: NextPage<Props> = ({ craftEssences }) => {
  const [selectedSorting, setSorting] = useState<SortOption>(SortOption.atkAsc);

  const sortingButtons = Object.values(SortOption).map((option) => {
    const style: CSSProperties = {};
    if (option === selectedSorting) {
      style.color = "blue";
    }

    return (
      <>
        <button
          key={option}
          style={style}
          onClick={() => {
            setSorting(option);
          }}
        >
          {option}
        </button>
      </>
    );
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Stop Hoarding</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Stop Hoarding</h1>
        <p>
          Includes all CEs which have effects for more than 1 event (reruns are
          a separate event ID). Click View Info to confirm affected events
        </p>
        <div className={styles["button-container"]}>{sortingButtons}</div>
        <CeList craftEssences={craftEssences} sortOption={selectedSorting} />
      </main>
    </div>
  );
};

export default Home;
