import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { CraftEssence } from "../types";
import fsPromises from "fs/promises";
import path from "path";
import { FixedSizeGrid as Grid } from "react-window";
import { CeCard } from "../components/CeCard";
import Image from "next/image";

type Props = {
  craftEssences: CraftEssence[];
};

export async function getStaticProps() {
  const filePath = path.join(process.cwd(), "public/results.json");
  const jsonData = await fsPromises.readFile(filePath);
  const craftEssences = JSON.parse(jsonData as unknown as string);

  return {
    props: {
      craftEssences,
    },
  };
}

const Home: NextPage<Props> = (props) => {
  const sortedCes = [...props.craftEssences];

  const colsCount = 5;
  const rowsCount = Math.floor(sortedCes.length / colsCount);

  // sort by ascending base atk
  sortedCes.sort((first, second) => {
    if (first.atkBase > second.atkBase) {
      return 1;
    } else {
      return -1;
    }
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Stop Hoarding</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Stop Hoarding</h1>
        <p>
          Sorted by ascending ATK. Includes all CEs which have effects for more
          than 1 event (reruns are a separate event ID). Click View Info to
          confirm affected events
        </p>
        <Grid<CraftEssence[]>
          columnCount={colsCount}
          columnWidth={250}
          rowCount={rowsCount}
          rowHeight={500}
          height={800}
          width={1250}
          itemData={sortedCes}
        >
          {CeCard}
        </Grid>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
